const cloudinary = require('cloudinary').v2;

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME || 'fixvo-demo',
  api_key: process.env.CLOUDINARY_API_KEY || '123456789',
  api_secret: process.env.CLOUDINARY_API_SECRET || 'secret123'
});

/**
 * Check if Cloudinary is configured with real (non-demo) credentials.
 */
const isCloudinaryConfigured = () => {
  return process.env.CLOUDINARY_CLOUD_NAME && 
         process.env.CLOUDINARY_CLOUD_NAME !== 'fixvo-demo' &&
         process.env.CLOUDINARY_API_KEY &&
         process.env.CLOUDINARY_API_KEY !== '123456789';
};

/**
 * Upload a public image to Cloudinary (e.g., job photos, avatars).
 * Falls back to returning the raw string if Cloudinary is not configured.
 */
const uploadImage = async (fileStr, folder = 'fixvo_jobs') => {
  try {
    if (!fileStr) return null;
    // If already a hosted HTTP/HTTPS URL, return as is
    if (fileStr.startsWith('http://') || fileStr.startsWith('https://')) {
      return fileStr;
    }
    
    if (isCloudinaryConfigured()) {
      const uploadResponse = await cloudinary.uploader.upload(fileStr, {
        folder,
        resource_type: 'auto'
      });
      return uploadResponse.secure_url;
    }
    
    return fileStr;
  } catch (error) {
    console.error('Cloudinary Upload Error:', error);
    return fileStr;
  }
};

/**
 * Upload a PRIVATE KYC document to Cloudinary.
 * Uses 'authenticated' type so direct public URLs are blocked.
 * Only accessible via signed URLs generated by getSignedDocumentUrl().
 * 
 * @param {string} fileStr - Base64 data URL or file path
 * @param {string} technicianId - Technician's userId for folder isolation
 * @param {string} docType - Document type: 'governmentId', 'selfie', 'addressProof', 'idProof'
 * @returns {Promise<{publicId: string, format: string}|null>} Upload result with publicId for DB storage
 */
const uploadPrivateDocument = async (fileStr, technicianId, docType) => {
  try {
    if (!fileStr) return null;

    // If already a URL, we can't move it to private storage — return a reference
    if (fileStr.startsWith('http://') || fileStr.startsWith('https://')) {
      return { publicId: fileStr, format: 'url_legacy' };
    }

    if (isCloudinaryConfigured()) {
      const uploadResponse = await cloudinary.uploader.upload(fileStr, {
        folder: `fixvo_kyc_private/${technicianId}`,
        resource_type: 'auto',
        type: 'authenticated',       // Private — no public URL access
        access_mode: 'authenticated', // Requires signed URL
        overwrite: true,
        public_id: docType,           // e.g., fixvo_kyc_private/<userId>/governmentId
        invalidate: true
      });
      return {
        publicId: uploadResponse.public_id,
        format: uploadResponse.format || 'jpg'
      };
    }
    
    // Development fallback: store a placeholder reference (NOT the raw base64)
    const placeholder = `dev_kyc_${technicianId}_${docType}_${Date.now()}`;
    console.warn(`⚠️  Cloudinary not configured — using dev placeholder: ${placeholder}`);
    return { publicId: placeholder, format: 'dev_placeholder' };
  } catch (error) {
    console.error('Cloudinary Private Upload Error:', error);
    throw new Error(`Failed to upload ${docType} document securely. Please try again.`);
  }
};

/**
 * Generate a time-limited signed URL for viewing a private KYC document.
 * URLs expire after the specified duration (default: 15 minutes).
 * 
 * @param {string} publicId - Cloudinary public_id stored in the Technician document
 * @param {Object} options - URL generation options
 * @param {number} options.expiresInSeconds - URL expiry time in seconds (default: 900 = 15 min)
 * @param {string} options.format - Image format (default: auto-detected from publicId)
 * @returns {string} Signed URL with expiry
 */
const getSignedDocumentUrl = (publicId, options = {}) => {
  if (!publicId) return null;

  // If it's a legacy URL (pre-migration), return it directly
  if (publicId.startsWith('http://') || publicId.startsWith('https://')) {
    return publicId;
  }

  // Development placeholder — return a generic placeholder image
  if (publicId.startsWith('dev_kyc_')) {
    return `https://placehold.co/400x300/1e293b/94a3b8?text=KYC+Doc+(Dev+Mode)`;
  }

  const { expiresInSeconds = 900 } = options;
  const expiresAt = Math.floor(Date.now() / 1000) + expiresInSeconds;

  try {
    return cloudinary.url(publicId, {
      type: 'authenticated',
      sign_url: true,
      secure: true,
      resource_type: 'image',
      expires_at: expiresAt
    });
  } catch (error) {
    console.error('Cloudinary Signed URL Error:', error);
    return null;
  }
};

/**
 * Delete a private KYC document from Cloudinary.
 * Used for document retention policy compliance and re-uploads.
 * 
 * @param {string} publicId - Cloudinary public_id to delete
 * @returns {Promise<boolean>} True if deletion succeeded
 */
const deleteDocument = async (publicId) => {
  if (!publicId || publicId.startsWith('http') || publicId.startsWith('dev_kyc_')) {
    return false;
  }

  try {
    if (isCloudinaryConfigured()) {
      const result = await cloudinary.uploader.destroy(publicId, {
        type: 'authenticated',
        resource_type: 'image',
        invalidate: true
      });
      return result.result === 'ok';
    }
    return true; // Dev mode — pretend deletion succeeded
  } catch (error) {
    console.error('Cloudinary Delete Error:', error);
    return false;
  }
};

module.exports = { 
  uploadImage, 
  uploadPrivateDocument, 
  getSignedDocumentUrl, 
  deleteDocument,
  isCloudinaryConfigured
};
